#!/bin/sh
# Cria o role dedicado da aplicação no primeiro boot do Postgres.
# RLS não se aplica a superuser/owner — a aplicação PRECISA deste role.
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<SQL
CREATE ROLE guilda_app LOGIN PASSWORD '${APP_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO guilda_app;
GRANT USAGE ON SCHEMA public TO guilda_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO guilda_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO guilda_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO guilda_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO guilda_app;
SQL
